language: cpp

compiler:
  - gcc

branches:
  only:
    - travis-build

matrix:
  include:
    - compiler: i686-w64-mingw32-g++
      env: OPTIONS="-DMINGW=ON"

install:
 - sudo apt-get -qq update
 - sudo apt-get -qq install libboost-dev binutils-mingw-w64-i686 g++-mingw-w64-i686 

script:
 - mkdir _build
 - cd _build
 - cmake ..
 - cmake --build .
